meals_on_wheels/core/urls.py
from django.urls import path
from .views import IndexView

app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

meals_on_wheels/meals_on_wheels/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.urls.conf import re_path
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('customers/', include('customers.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
]

# if settings.DEBUG:
#     urlpatterns += [
#                     re_path(r'^media/(?P<path>.*)$',
#                     serve,
#                     {'document_root': settings.MEDIA_ROOT}),
#     ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meals_on_wheels/orders/urls.py
from django.urls import path
from .views import CartView
from .views import CheckoutView
from .views import ThankYouView

app_name = 'orders'

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('thank_you/', ThankYouView.as_view(), name='thank_you'),
]

meals_on_wheels/products/urls.py
from django.urls import path
from products.views import ProductListView, ProductDetailView

app_name = 'products'

urlpatterns = [
    path('menu/', ProductListView.as_view(), name='menu'),
    path('product/<int:product_id>',
         ProductDetailView.as_view(),
         name='product'
         ),
]

meals_on_wheels/orders/models.py
from django.db import models
from django.db.models.deletion import DO_NOTHING, SET_NULL
from products.models import Product
from customers.models import Customer


class Order(models.Model):
    customer = models.ForeignKey(
                                 Customer,
                                 on_delete=DO_NOTHING,
                                 related_name='history',
                                 blank=True,
                                 null=True,
                                 )
    total = models.DecimalField(
                                max_digits=12,
                                decimal_places=2,
                                blank=True,
                                null=True,
                                )
    payment_option = models.CharField(
                                      max_length=100,
                                      blank=True,
                                      null=True,
                                      )
    opened_on = models.DateTimeField(auto_now_add=True)
    closed_on = models.DateTimeField(auto_now=True)
    completed = models.BooleanField(default=False)


class ItemInCart(models.Model):
    product = models.ForeignKey(
                                Product,
                                on_delete=SET_NULL,
                                blank=True,
                                null=True,
                                )
    customer = models.ForeignKey(
                                 Customer,
                                 on_delete=SET_NULL,
                                 blank=True,
                                 null=True,
                                 related_name='cart'
                                 )
    order = models.ForeignKey(
                              Order,
                              on_delete=SET_NULL,
                              blank=True,
                              null=True,
                              related_name='items'
                              )
    quantity = models.PositiveSmallIntegerField(blank=True)

    def __str__(self):
        return self.product

    class Meta:
        verbose_name = 'items in cart'

meals_on_wheels/orders/views.py
from django.views.generic.list import ListView
from django.views.generic import TemplateView
from products.models import Product
from .models import ItemInCart


class CartView(ListView):
    model = ItemInCart
    context_object_name = 'item'
    template_name = 'orders/cart.html'


class CheckoutView(TemplateView):
    template_name = 'orders/checkout.html'


class ThankYouView(ListView):
    model = Product
    context_object_name = 'products'
    template_name = 'orders/thank_you.html'

    def get_queryset(self):
        return super().get_queryset().order_by('-views')[:5]

meals_on_wheels/orders/templates/orders/cart.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}

<div class="row">
    <div class="col-lg-12">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'products:menu' %}">&#8592; Back to Menu</a>
            <br>
            <table class="table">
                <tr>
                    <th><h5>Items: <strong>3</strong></h5></th>
                    <th><h5>Total: <strong>$45</strong></h5></th>
                    <th>
                        <a style="float:right; margin:5px" class="btn btn-outline-success" href="{% url 'orders:checkout' %}">Checkout</a>
                    </th>
                </tr>
            </table>
        
        </div>

        <br>

        <div class="box-element">
            <div class="cart-row" style="font-weight: 600;">
                <div style="flex:2"></div>
                <div style="flex:2">Item</div>
                <div style="flex:1">Price</div>
                <div style="flex:1">Quantity</div>
                <div style="flex:1">Total</div>
            </div>

            <div class="cart-row">
                <div style="flex:2">
                    <img class="row-image" src="{% static 'images/products/chicken_avocado_salad.jpg' %}" alt="">
                </div>
                <div style="flex:2">Product 1</div>
                <div style="flex:1">$10</div>
                <div style="flex:1">
                    <span class="quantity">3</span>
                    <div class="quantity">
                        <span class="chg-quantity">&#43;</span>
                        <span class="chg-quantity">&#8722;</span>
                    </div>
                </div>
                <div style="flex:1">$45</div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

meals_on_wheels/orders/templates/orders/checkout.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}

<div class="row">
    <div class="col-lg-6">
        <div class="box-element" id="form-wrapper">
            <form id="form" action="#">
                <div id="user-info">
                    <div class="form-field">
                        <input required class="form-control" type="text" name="name" placeholder="Name..">
                    </div>
                    <div class="form-field">
                        <input required class="form-control" type="email" name="email" placeholder="Email..">
                    </div>
                </div>
                <div id="shipping-info">
                    <hr>
                    <p>Delivery Information:</p>
                    <hr>
                    <div class="form-field">
                        <input class="form-control" type="text" name="address" placeholder="Address..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="city" placeholder="City..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="state" placeholder="State..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="country" placeholder="Zip code..">
                    </div>
                </div>

                <hr>
                <input id="form-button" class="btn btn-success w-100" type="submit" value="Continue">
            </form>
        </div>
        <br>

        <div class="box-element hidden" id="payment-info">
            <small>Payment Options</small>

        </div>
    </div>
    <div class="col-lg-6">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'orders:cart' %}">&#8592; Back to Cart</a>
            <hr>
            <h3>Order Summary</h3>
            <hr>

            <div class="cart-row">
                <div style="flex:2"><img class="row-image" src="{% static 'images/placeholder.png' %}"></div>
                <div style="flex:2"><p>Product 1</p></div>
                <div style="flex:1"><p>$20.00</p></div>
                <div style="flex:1"><p>x2</p></div>
            </div>
            <h5>Items: 3</h5>
            <h5>Total: $45</h5>
        </div>
    </div>
</div>

{% endblock content %}

meals_on_wheels/orders/templates/orders/thank_you.html
{% extends 'core/base.html' %}

{% block content %}

<h1>Thank You!</h1>
<h3>We'll make sure you get your order as soon as possible.</h3>
<h3>In the meantime, you might want to check out our 5 top-selling items:</h3>

<div class='row'>
{% for product in products %}
{{ product.name }}
    <div class="col-lg-4">
        <p><a href="{% url 'products:product' product_id=product.id %}">
            <img class="thumbnail" src="{{ product.imageURL }}" alt="{{ product.name }}">
        </a>
        </p>
        <div class="box-element product">
            <p><h6><strong><a href="{% url 'products:product' product_id=product.id %}">{{ product.name }}</a></strong></h6></p>
            <p>{{ product.overview }}</p>
            <hr>
            <button class="btn btn-outline-secondary add-btn">Add to Cart</button>
            <h4 style="float: right">${{ product.price }}</h4>
        </div>
    </div>
{% endfor %}
</div>


{% endblock content %}