meals_on_wheels/core/urls.py
from django.urls import path
from .views import IndexView

app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

meals_on_wheels/meals_on_wheels/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.urls.conf import re_path
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('customers/', include('customers.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
]

# if settings.DEBUG:
#     urlpatterns += [
#                     re_path(r'^media/(?P<path>.*)$',
#                     serve,
#                     {'document_root': settings.MEDIA_ROOT}),
#     ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meals_on_wheels/products/urls.py
from django.urls import path
from products.views import ProductListView, ProductDetailView

app_name = 'products'

urlpatterns = [
    path('menu/', ProductListView.as_view(), name='menu'),
    path('product/<int:product_id>',
         ProductDetailView.as_view(),
         name='product'
         ),
]

meals_on_wheels/products/models.py
from django.db import models
from django.db.models.deletion import CASCADE


class Product(models.Model):
    name = models.CharField(max_length=100)
    overview = models.TextField(
                                max_length=200,
                                blank=True,
                                null=True,
                                )
    description = models.TextField(
                                   max_length=500,
                                   blank=True,
                                   null=True,
                                   )
    price = models.DecimalField(
                                max_digits=12,
                                decimal_places=2,
                                blank=True,
                                )
    category = models.ManyToManyField(
                                      'Category',
                                      related_name='products',
                                      )
    ingredient = models.ManyToManyField(
                                        'Ingredient',
                                        related_name='products'
                                        )
    cover_image = models.ImageField(blank=True, null=True)
    views = models.IntegerField(default=0, blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    # quantity_in_stock = models.IntegerField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-date_added', '-views', 'name']

    @property
    def imageURL(self):
        try:
            url = self.cover_image.url
        except:
            url = ''
        return url


class Category(models.Model):
    name = models.CharField(max_length=100)
    ordinal = models.PositiveSmallIntegerField(blank=True, null=True)

    class Meta:
        verbose_name_plural = 'categories'
        ordering = ['ordinal']

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Photo(models.Model):
    image = models.ImageField(blank=True, null=True)
    product = models.ForeignKey(
                                Product,
                                on_delete=CASCADE,
                                related_name='photos'
                                )

meals_on_wheels/products/views.py
from django.views.generic.list import ListView
from django.views.generic import DetailView
from products.models import Product


class ProductListView(ListView):
    model = Product
    context_object_name = 'products'
    template_name = 'products/menu.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        if 'category' in self.request.GET:
            queryset = queryset.filter(
                       category=self.request.GET['category']
                                       )
        return queryset


class ProductDetailView(DetailView):
    model = Product
    template_name = 'product.html'
    pk_url_kwarg = 'product_id'

    def get(self, request, product_id):
        response = super().get(request)
        self.object.views += 1
        self.object.save()
        return response

meals_on_wheels/products/templates/products/menu.html
{% extends 'core/base.html' %}
{% load products_tags %}
{% block content %}

<div>
    {% category_list %}
</div>

<div class='row'>
    {% for product in products %}
    <div class="col-lg-4">
        <p><a href="{% url 'products:product' product_id=product.id %}">
            <img class="thumbnail" src="{{ product.imageURL }}" alt="{{ product.name }}">
           </a>
        </p>
        <div class="box-element product">
            <p><h6><strong><a href="{% url 'products:product' product_id=product.id %}">{{ product.name }}</a></strong></h6></p>
            <p>{{ product.overview }}</p>
            <hr>
            <button class="btn btn-outline-secondary add-btn">Add to Cart</button>
            <h4 style="float: right">${{ product.price }}</h4>
        </div>
    </div>
    {% endfor %}
</div>

<div>

</div>

{% endblock content %}

meals_on_wheels/products/templates/products/product.html
{% extends 'core/base.html' %}

{% block content %}

<div>
    <p>{{ product.name }}</p>
    <p><img src="{{ product.cover_image.url }}" alt="cover_image"></p>
    <p>{{ product.price }}</p>
    <p>{{ product.description }}</p>
    {% for ingredient in product.ingredients %}
    <ul>
        <li>{{ ingredient }}</li>
    </ul>
</div>

{% endblock content %}