meals_on_wheels/core/urls.py
from django.urls import path
from .views import IndexView

app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

meals_on_wheels/customers/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import LoginCustomerView
from .views import ProfileDetailsView
from .views import ProfileEditView
from .views import RegisterView
from .views import CustomPasswordChangeView

app_name = 'customers'

urlpatterns = [
    path('login/',
         LoginCustomerView.as_view(),
         name='login'
         ),
    path('logout/',
         LogoutView.as_view(),
         name='logout'
         ),
    path('register/',
         RegisterView.as_view(),
         name='register'
         ),
    path('profile-details/',
         ProfileDetailsView.as_view(),
         name='profile-details'
         ),
    path('profile-edit/',
         ProfileEditView.as_view(),
         name='profile-edit'
         ),
    path('password-change/',
         CustomPasswordChangeView.as_view(),
         name='password-change'
         ),
]

meals_on_wheels/meals_on_wheels/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.urls.conf import re_path
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('customers/', include('customers.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
]

# if settings.DEBUG:
#     urlpatterns += [
#                     re_path(r'^media/(?P<path>.*)$',
#                     serve,
#                     {'document_root': settings.MEDIA_ROOT}),
#     ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meals_on_wheels/orders/urls.py
from django.urls import path
from .views import CartView
from .views import CheckoutView
from .views import ThankYouView

app_name = 'orders'

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('thank_you/', ThankYouView.as_view(), name='thank_you'),
]

meals_on_wheels/products/urls.py
from django.urls import path
from products.views import ProductListView, ProductDetailView

app_name = 'products'

urlpatterns = [
    path('menu/', ProductListView.as_view(), name='menu'),
    path('product/<int:product_id>',
         ProductDetailView.as_view(),
         name='product'
         ),
]

meals_on_wheels/core/models.py
from django.db import models

# Create your models here.

meals_on_wheels/core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'core/index.html'

meals_on_wheels/core/templates/core/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meals on Wheels</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}" media="all">
</head>
<body>

    {% include 'core/navbar.html' %}
    
    <div class='container'>
        {% block content %}
        
        {% endblock content %}
    </div>
        
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

meals_on_wheels/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block content %}

<h2>Welcome to the Meals on Wheels project!</h2>

<a href="{% url 'products:menu' %}">GO TO MENU</a>

{% endblock content %}

meals_on_wheels/core/templates/core/navbar.html
{% load static %}

<!-- <h1><a href="{% url 'core:index' %}">MEALS ON WHEELS</a></h1> -->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'core:index' %}">Meals on Wheels</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'products:menu' %}">Menu</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Profile
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">View Profile</a></li>
              <li><a class="dropdown-item" href="#">History</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Logout</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
          {% if request.user.is_authenticated %}
          <li>
            Hello, {% if request.user.first_name %} {{ request.user.first_name }}!
              {% else %}{{ request.user.username }}!{% endif %}
              <a href="{% url 'customers:logout' %}">LOGOUT</a>
              {% else %}
              <a href="{% url 'customers:login' %}">LOGIN</a>
            </li>
            {% endif %}
        </ul>
        <!-- <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form> -->
        <div class="form-inline my-2 my-lg-0">
            {% if request.user.is_authenticated %}
            <span><a href="{% url 'customers:profile-details' %}">My Profile</a></span>
            <a href="{% url 'customers:logout' %}"class="btn btn-warning">Logout</a>
            {% else %}
            <a href="{% url 'customers:login' %}">LOGIN</a>
            {% endif %}

            <a href="{% url 'orders:cart' %}">
               <img  id="cart-icon" src="{% static 'images/shopping_bag.png' %}">
           </a>
           <p id="cart-total">0</p>
       </div>
      </div>
    </div>
</nav>
<!-- {% if request.user.is_authenticated %}
    <p>Hello, {% if request.user.first_name %} {{ request.user.first_name }}!
              {% else %}{{ request.user.username }}!{% endif %}</p>
    <a href="{% url 'customers:logout' %}">LOGOUT</a>
    <span><a href="{% url 'customers:profile-details' %}">My Profile</a></span>
{% else %}
    <a href="{% url 'customers:login' %}">LOGIN</a>
{% endif %} -->

<!-- <img src="{% static 'images/shopping_bag.png' %}" alt=""> -->

<hr>