meals_on_wheels/core/urls.py
from django.urls import path
from .views import IndexView

app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

meals_on_wheels/customers/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import LoginCustomerView
from .views import ProfileDetailsView
from .views import ProfileEditView
from .views import RegisterView
from .views import CustomPasswordChangeView

app_name = 'customers'

urlpatterns = [
    path('login/',
         LoginCustomerView.as_view(),
         name='login'
         ),
    path('logout/',
         LogoutView.as_view(),
         name='logout'
         ),
    path('register/',
         RegisterView.as_view(),
         name='register'
         ),
    path('profile-details/',
         ProfileDetailsView.as_view(),
         name='profile-details'
         ),
    path('profile-edit/',
         ProfileEditView.as_view(),
         name='profile-edit'
         ),
    path('password-change/',
         CustomPasswordChangeView.as_view(),
         name='password-change'
         ),
]

meals_on_wheels/meals_on_wheels/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.urls.conf import re_path
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('customers/', include('customers.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
]

# if settings.DEBUG:
#     urlpatterns += [
#                     re_path(r'^media/(?P<path>.*)$',
#                     serve,
#                     {'document_root': settings.MEDIA_ROOT}),
#     ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meals_on_wheels/customers/models.py
from django.db import models
# from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db.models.deletion import CASCADE
from django.db.models.fields import CharField


class Customer(AbstractUser):
    phone = models.CharField(max_length=20, blank=True)
    city = models.CharField(max_length=225, blank=True)
    street_address = models.CharField(max_length=225, blank=True)
    bonus_account = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.username


class BankCard(models.Model):
    number = models.CharField(max_length=16)
    expiration_date = models.DateField()
    secret_code = CharField(max_length=3)
    customer = models.ForeignKey(
                                 Customer,
                                 on_delete=CASCADE,
                                 blank=True,
                                 null=True,
                                 related_name='cards'
                                 )

    def __str__(self):
        return self.number

meals_on_wheels/customers/forms.py
from django.contrib.auth import get_user_model
from django.forms import ModelForm
from django.forms import widgets


class ProfileForm(ModelForm):
    class Meta:
        model = get_user_model()
        fields = (
                  'username',
                  'phone',
                  'first_name',
                  'last_name',
                  'email',
                  'city',
                  'street_address'
                  )

        widgets = {
                   'email':
                   widgets.EmailInput(attrs={
                                            'placeholder':
                                            'Type in your email address',
                                            }),
                   'first_name':
                   widgets.TextInput(attrs={
                                           'placeholder':
                                           'Type in your first name',
                                           }),
                   'last_name':
                   widgets.TextInput(attrs={
                                           'placeholder':
                                           'Type in your last name',
                                           }),
                   'phone':
                   widgets.TextInput(attrs={
                                           'placeholder':
                                           'Type in your phone number',
                                           }),
                   'city':
                   widgets.TextInput(attrs={
                                           'placeholder':
                                           'Type in your city',
                                           }),
                   'street_address':
                   widgets.TextInput(attrs={
                                           'placeholder':
                                           'Type in your street address',
                                           }),
        }

        labels = {
                'email': 'Email',
        }

meals_on_wheels/customers/views.py
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth.views import LoginView
from django.contrib.auth import get_user_model
from django.contrib.auth import login
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import SetPasswordForm
from django.contrib import messages
from django.views.generic import DetailView
from django.views.generic.edit import FormView
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from .forms import ProfileForm


class LoginCustomerView(LoginView):
    template_name = 'customers/login_register.html'
    page = 'login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = self.page
        return context


class RegisterView(FormView):
    template_name = 'customers/login_register.html'
    success_url = '/'

    class CustomUserCreationForm(UserCreationForm):
        class Meta:
            model = get_user_model()
            fields = ("username",)
            field_classes = {'username': UsernameField}

    form_class = CustomUserCreationForm

    def form_valid(self, form):
        form.save()
        login(self.request, get_user_model()
              .objects.get(username=self.request.POST['username']))
        return super().form_valid(form)


class ProfileDetailsView(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy('customers:login')
    template_name = 'customers/profile.html'
    model = get_user_model()
    context_object_name = 'customer'
    page = 'profile_details'

    def get_object(self):
        return get_user_model().objects.get(pk=self.request.user.pk)

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        context['page'] = self.page
        return context


class ProfileEditView(LoginRequiredMixin, FormView):
    login_url = reverse_lazy('customers:login')
    template_name = 'customers/profile.html'
    form_class = ProfileForm
    success_url = reverse_lazy('customers:profile-details')

    def form_invalid(self, form):
        messages.error(self.request, 'Something went wrong...')
        return self.render_to_response(self.get_context_data(form=form))

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_form_kwargs(self) -> dict:
        kwargs = super().get_form_kwargs()
        kwargs['instance'] = get_object_or_404(
                                               get_user_model(),
                                               pk=self.request.user.pk
                                               )
        return kwargs


class CustomPasswordChangeView(LoginRequiredMixin, FormView):
    login_url = reverse_lazy('customers:login')
    template_name = 'customers/password_change.html'
    form_class = SetPasswordForm

    def get_form_kwargs(self) -> dict:
        kwargs = super().get_form_kwargs()
        kwargs['user'] = get_object_or_404(get_user_model(),
                                           pk=self.request.user.id
                                           )
        return kwargs

    def form_valid(self, form):
        user = form.save()
        update_session_auth_hash(self.request, user)
        messages.success(self.request,
                         'Your password has been successfully updated!'
                         )
        return redirect(reverse_lazy('customers:profile-details'))

meals_on_wheels/customers/templates/customers/history.html
{% extends 'core/base.html' %}

{% block content %}



{% endblock content %}

meals_on_wheels/customers/templates/customers/login_register.html
{% extends 'core/base.html' %}

{% block content %}

{% if page == 'login' %}

<form action="" method="POST">
    {% csrf_token %}
    <div>
        <p>{{ form.username.label }}:</p>
        <p>{{ form.username }}</p>
    </div>
    <div>
        <p>{{ form.password.label }}:</p>
        <p>{{ form.password }}</p>
    </div>
    <button type="submit">Log in</button>
</form>

<p>Not registered yet?</p>
<a href="{% url 'customers:register' %}">Register</a>

{% else %}

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
</form>

<p>Already registered?</p>
<a href="{% url 'customers:login' %}">Log in</a>

{% endif %}

{% endblock content %}

meals_on_wheels/customers/templates/customers/password_change.html
{% extends 'core/base.html' %}

{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    {% if messages %}
    {% for message in messages %}
    {{ message }}
    {% endfor %}
    {% endif %}
    <p>{{ form.as_p }}</p>
    <button type="submit">Save</button>
</form>
<hr>

{% endblock content %}

meals_on_wheels/customers/templates/customers/profile.html
{% extends 'core/base.html' %}

{% block content %}

{% if page == 'profile_details' %}
<div>
    <a href="{% url 'customers:profile-edit' %}">Edit</a>
    <hr>
    <p>Personal Details</p>
    <p>User Name: {{ customer.username }}</p>
    <p>Email: {% if customer.email %}{{ customer.email }}{% else %}<span style="font-style: italic;">please provide by editing your profile</span>{% endif %}</p>
    <p>First Name: {% if customer.first_name %}{{ customer.first_name }}{% else %}<span style="font-style: italic;">please provide by editing your profile</span>{% endif %}</p>
    <p>Last Name: {% if customer.last_name %}{{ customer.last_name }}{% else %}<span style="font-style: italic;">please provide by editing your profile</span>{% endif %}</p>
    <p>Phone: {% if customer.phone %}{{ customer.phone }}{% else %}<span style="font-style: italic;">please provide by editing your profile</span>{% endif %}</p>
    <p>City: {% if customer.city %}{{ customer.city }}{% else %}<span style="font-style: italic;">please provide by editing your profile</span>{% endif %}</p>
    <p>Street Address: {% if customer.street_address %}{{ customer.street_address }}{% else %}<span style="font-style: italic;">please provide by editing your profile</span>{% endif %}</p>
    <hr>
</div>
{% else %}
<div>
    <form action="" method="POST">
        {% csrf_token %}

        <div>
            <p>{{ form.username.label }}:</p>
            <p>{{ form.username }}</p>
        </div>
        <div>
            <p>{{ form.email.label }}:</p>
            <p>{{ form.email }}</p>
        </div>
        <div>
            <p>{{ form.first_name.label }}:</p>
            <p>{{ form.first_name }}</p>
        </div>
        <div>
            <p>{{ form.last_name.label }}:</p>
            <p>{{ form.last_name }}</p>
        </div>
        <div>
            <p>{{ form.phone.label }}:</p>
            <p>{{ form.phone }}</p>
        </div>
        <div>
            <p>{{ form.city.label }}:</p>
            <p>{{ form.city }}</p>
        </div>
        <div>
            <p>{{ form.street_address.label }}:</p>
            <p>{{ form.street_address }}</p>
        </div>
        <button type='submit'>Save</button>
    </form>
    <hr>
    <a href="{% url 'customers:password-change' %}">Change Password</a>
</div>
{% endif %}

{% endblock content %}